/**
 * Copyright 2026 Oscar Yáñez Cisterna (@SkrOYC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface FixtureEntry {
  fixtureId: string;
  relativePath: string;
}

interface PlanCheck {
  assertions: Array<Record<string, unknown>>;
  capabilities?: string[];
  checkId: string;
  evidence?: string[];
  fixture?: string;
  input?: Record<string, unknown>;
  operation: string;
}

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const PLANS_DIR = resolve(REPO_ROOT, "boundaries/kernel/conformance/plans");

// Fixture inventory generated by generate-kernel-fixtures.ts plus the
// preexisting canonical fixture. Each fixture exercises both
// deterministic-hashing and schema-roundtrip operations.
const fixtures: FixtureEntry[] = [
  {
    fixtureId: "f-empty-bytes",
    relativePath: "../fixtures/kernel-protocol-empty-bytes.json",
  },
  {
    fixtureId: "f-single-byte",
    relativePath: "../fixtures/kernel-protocol-single-byte.json",
  },
  {
    fixtureId: "f-all-zero-bytes",
    relativePath: "../fixtures/kernel-protocol-all-zero-bytes.json",
  },
  {
    fixtureId: "f-all-ones-bytes",
    relativePath: "../fixtures/kernel-protocol-all-ones-bytes.json",
  },
  {
    fixtureId: "f-large-bytes",
    relativePath: "../fixtures/kernel-protocol-large-bytes.json",
  },
  {
    fixtureId: "f-multi-path-schema",
    relativePath: "../fixtures/kernel-protocol-multi-path-schema.json",
  },
  {
    fixtureId: "f-all-single-paths",
    relativePath: "../fixtures/kernel-protocol-all-single-paths-schema.json",
  },
  {
    fixtureId: "f-all-ordered-paths",
    relativePath: "../fixtures/kernel-protocol-all-ordered-paths-schema.json",
  },
  {
    fixtureId: "f-with-prev-turn",
    relativePath: "../fixtures/kernel-protocol-with-prev-turn.json",
  },
  {
    fixtureId: "f-with-event-hash",
    relativePath: "../fixtures/kernel-protocol-with-event-hash.json",
  },
  {
    fixtureId: "f-staged-failed",
    relativePath: "../fixtures/kernel-protocol-staged-result-failed.json",
  },
  {
    fixtureId: "f-staged-interrupted",
    relativePath: "../fixtures/kernel-protocol-staged-result-interrupted.json",
  },
  {
    fixtureId: "f-many-staged-results",
    relativePath: "../fixtures/kernel-protocol-many-staged-results.json",
  },
  {
    fixtureId: "f-deep-path-schema",
    relativePath: "../fixtures/kernel-protocol-deep-path-schema.json",
  },
  {
    fixtureId: "f-non-utf8-bytes",
    relativePath: "../fixtures/kernel-protocol-non-utf8-bytes.json",
  },
  {
    fixtureId: "f-zero-turn-tree-hash",
    relativePath: "../fixtures/kernel-protocol-zero-turn-tree-hash.json",
  },
  {
    fixtureId: "f-mixed-status-staged",
    relativePath: "../fixtures/kernel-protocol-mixed-status-staged-results.json",
  },
];

interface CoverageProbe {
  evidencePaths: string[];
  operation: string;
}

// Kernel syscall surface (28 operations) per docs/KrakenKernelSpecification.md
// §7. Adapters today expose only 7 operations; probing the missing 21 catches
// implementations that claim a kernel capability without backing the full
// surface.
const missingKernelOperations: string[] = [
  "kernel.store.put",
  "kernel.store.get",
  "kernel.store.has",
  "kernel.schema.register",
  "kernel.schema.get",
  "kernel.tree.create",
  "kernel.tree.incorporate",
  "kernel.tree.diff",
  "kernel.tree.resolve",
  "kernel.tree.manifest",
  "kernel.node.get",
  "kernel.node.walk-back",
  "kernel.thread.create",
  "kernel.thread.get",
  "kernel.branch.create",
  "kernel.branch.get",
  "kernel.branch.set-head",
  "kernel.staging.stage",
  "kernel.staging.current",
  "kernel.run.create",
  "kernel.run.begin-step",
  "kernel.run.complete-step",
  "kernel.run.complete-run",
  "kernel.run.recover",
  "kernel.verdicts.compose",
  "kernel.turn.create",
  "kernel.turn.get",
  "kernel.turn.update-head",
];

const syscallCoverageProbesInline: CoverageProbe[] = [
  { evidencePaths: ["store.objectHash"], operation: "kernel.store.put" },
  { evidencePaths: ["store.exists"], operation: "kernel.store.has" },
  { evidencePaths: ["store.blobLength"], operation: "kernel.store.get" },
  { evidencePaths: ["schema.schemaId"], operation: "kernel.schema.register" },
  { evidencePaths: ["schema.paths"], operation: "kernel.schema.get" },
  { evidencePaths: ["tree.turnTreeHash"], operation: "kernel.tree.create" },
  {
    evidencePaths: ["tree.turnTreeHash", "tree.consumedTaskIds"],
    operation: "kernel.tree.incorporate",
  },
  { evidencePaths: ["tree.changedPaths"], operation: "kernel.tree.diff" },
  { evidencePaths: ["tree.pathValue"], operation: "kernel.tree.resolve" },
  { evidencePaths: ["tree.manifestPaths"], operation: "kernel.tree.manifest" },
  { evidencePaths: ["node.turnTreeHash"], operation: "kernel.node.get" },
  { evidencePaths: ["node.walkLength"], operation: "kernel.node.walk-back" },
  {
    evidencePaths: ["thread.threadId", "thread.rootTurnNodeHash"],
    operation: "kernel.thread.create",
  },
  { evidencePaths: ["thread.schemaId"], operation: "kernel.thread.get" },
  {
    evidencePaths: ["branch.branchId", "branch.headTurnNodeHash"],
    operation: "kernel.branch.create",
  },
  { evidencePaths: ["branch.threadId"], operation: "kernel.branch.get" },
  {
    evidencePaths: ["branch.direction", "branch.archiveBranchId"],
    operation: "kernel.branch.set-head",
  },
  {
    evidencePaths: ["staging.stagedResult.taskId"],
    operation: "kernel.staging.stage",
  },
  {
    evidencePaths: ["staging.uncommittedCount"],
    operation: "kernel.staging.current",
  },
  {
    evidencePaths: ["run.runId", "run.status"],
    operation: "kernel.run.create",
  },
  {
    evidencePaths: ["run.stepContext.stepId"],
    operation: "kernel.run.begin-step",
  },
  {
    evidencePaths: ["run.checkpoint.checkpointed"],
    operation: "kernel.run.complete-step",
  },
  {
    evidencePaths: ["run.completion.status"],
    operation: "kernel.run.complete-run",
  },
  {
    evidencePaths: [
      "run.recovery.lastTurnNodeHash",
      "run.recovery.lastCompletedStepId",
    ],
    operation: "kernel.run.recover",
  },
  {
    evidencePaths: ["verdicts.composedKind"],
    operation: "kernel.verdicts.compose",
  },
  {
    evidencePaths: ["turn.turnId", "turn.startTurnNodeHash"],
    operation: "kernel.turn.create",
  },
  { evidencePaths: ["turn.parentTurnId"], operation: "kernel.turn.get" },
  {
    evidencePaths: ["turn.headTurnNodeHash"],
    operation: "kernel.turn.update-head",
  },
];

await main();

async function main(): Promise<void> {
  const extendedPlan = buildExtendedProtocolPlan();
  const surfacePlan = buildSyscallSurfacePlan();
  const coveragePlan = buildSyscallCoveragePlan();

  await writeFile(
    resolve(PLANS_DIR, "kernel-protocol-extended.json"),
    `${JSON.stringify(extendedPlan, null, 2)}\n`
  );
  await writeFile(
    resolve(PLANS_DIR, "kernel-syscall-surface.json"),
    `${JSON.stringify(surfacePlan, null, 2)}\n`
  );
  await writeFile(
    resolve(PLANS_DIR, "kernel-syscall-coverage.json"),
    `${JSON.stringify(coveragePlan, null, 2)}\n`
  );

  process.stdout.write(
    `wrote kernel-protocol-extended.json (${extendedPlan.checks.length} checks)\n`
  );
  process.stdout.write(
    `wrote kernel-syscall-surface.json (${surfacePlan.checks.length} checks)\n`
  );
  process.stdout.write(
    `wrote kernel-syscall-coverage.json (${coveragePlan.checks.length} checks)\n`
  );
}

function buildExtendedProtocolPlan(): {
  applicability: { capabilities: string[] };
  checks: PlanCheck[];
  fixtures: Record<string, string>;
  packetId: string;
  planId: string;
  planVersion: string;
} {
  const checks: PlanCheck[] = [];

  for (const fixture of fixtures) {
    checks.push(
      buildDeterministicHashingCheck(fixture),
      buildSchemaRoundtripCheck(fixture)
    );
  }

  return {
    applicability: { capabilities: ["kernel.protocol"] },
    checks,
    fixtures: Object.fromEntries(
      fixtures.map((entry) => [entry.fixtureId, entry.relativePath])
    ),
    packetId: "tuvren.kernel.protocol",
    planId: "tuvren.kernel.protocol.extended",
    planVersion: "0.1.0",
  };
}

function buildDeterministicHashingCheck(fixture: FixtureEntry): PlanCheck {
  return {
    assertions: [
      {
        equalsPath: "$.fixture.rawOpaqueBytesSha256Hex",
        field: "$.hashes.rawOpaqueBytes",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnTreeSchemaRecordSha256Hex",
        field: "$.hashes.turnTreeSchema",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnNodeIdentityRecordSha256Hex",
        field: "$.hashes.turnNodeIdentity",
        kind: "evidenceField",
      },
    ],
    checkId: `kernel.protocol.deterministic_hashing.${fixture.fixtureId}`,
    evidence: [
      "hashes.rawOpaqueBytes",
      "hashes.turnTreeSchema",
      "hashes.turnNodeIdentity",
    ],
    fixture: fixture.fixtureId,
    operation: "kernel.protocol.deterministic-hashing",
  };
}

function buildSchemaRoundtripCheck(fixture: FixtureEntry): PlanCheck {
  return {
    assertions: [
      {
        equalsPath: "$.fixture.turnTreeSchemaRecord.schemaId",
        field: "$.roundtrip.turnTreeSchemaRecord.schemaId",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnNodeIdentityRecord.schemaId",
        field: "$.roundtrip.turnNodeIdentityRecord.schemaId",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnNodeIdentityRecord.turnTreeHash",
        field: "$.roundtrip.turnNodeIdentityRecord.turnTreeHash",
        kind: "evidenceField",
      },
    ],
    checkId: `kernel.protocol.schema_roundtrip.${fixture.fixtureId}`,
    evidence: [
      "roundtrip.turnTreeSchemaRecord.schemaId",
      "roundtrip.turnNodeIdentityRecord.schemaId",
      "roundtrip.turnNodeIdentityRecord.turnTreeHash",
    ],
    fixture: fixture.fixtureId,
    operation: "kernel.protocol.schema-roundtrip",
  };
}

function buildSyscallSurfacePlan(): {
  applicability: { capabilities: string[] };
  checks: PlanCheck[];
  packetId: string;
  planId: string;
  planVersion: string;
} {
  // Surface probe: each missing operation must answer the runner with a
  // protocol-correct error envelope. Adapters that crash, hang, or echo
  // freeform diagnostics fail this lane.
  const checks: PlanCheck[] = missingKernelOperations.map((operation) => ({
    assertions: [
      {
        field: "$.result.error",
        kind: "errorEnvelope",
        path: "$.state.adapterError",
      },
    ],
    capabilities: ["kernel.protocol"],
    checkId: `kernel.surface.${operation.replace(/\./g, "_")}`,
    evidence: ["adapterError.code"],
    operation,
  }));

  return {
    applicability: { capabilities: ["kernel.protocol"] },
    checks,
    packetId: "tuvren.kernel.protocol",
    planId: "tuvren.kernel.protocol.syscall-surface",
    planVersion: "0.1.0",
  };
}

function buildSyscallCoveragePlan(): {
  applicability: { capabilities: string[] };
  checks: PlanCheck[];
  packetId: string;
  planId: string;
  planVersion: string;
} {
  // Coverage probe: each operation must produce specific evidence keys for the
  // runner to consider the syscall implemented. Adapters that ignore the
  // operation, return only an error envelope, or omit the evidence shape will
  // fail this lane — these are the gaps we want surfaced.
  const checks: PlanCheck[] = syscallCoverageProbesInline.map((probe) => ({
    assertions: probe.evidencePaths.map((path) => ({
      field: `$.${path}`,
      kind: "evidenceField",
    })),
    capabilities: ["kernel.protocol"],
    checkId: `kernel.coverage.${probe.operation.replace(/\./g, "_")}`,
    evidence: probe.evidencePaths,
    operation: probe.operation,
  }));

  return {
    applicability: { capabilities: ["kernel.protocol"] },
    checks,
    packetId: "tuvren.kernel.protocol",
    planId: "tuvren.kernel.protocol.syscall-coverage",
    planVersion: "0.1.0",
  };
}
