/**
 * Copyright 2026 Oscar Yáñez Cisterna (@SkrOYC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface FixtureEntry {
  fixtureId: string;
  relativePath: string;
}

interface PlanCheck {
  assertions: Array<Record<string, unknown>>;
  capabilities?: string[];
  checkId: string;
  evidence?: string[];
  fixture?: string;
  input?: Record<string, unknown>;
  operation: string;
}

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const PLANS_DIR = resolve(REPO_ROOT, "boundaries/kernel/conformance/plans");

// Fixture inventory generated by generate-kernel-fixtures.ts plus the
// preexisting canonical fixture. Each fixture exercises both
// deterministic-hashing and schema-roundtrip operations.
const fixtures: FixtureEntry[] = [
  {
    fixtureId: "f-empty-bytes",
    relativePath: "../fixtures/kernel-protocol-empty-bytes.json",
  },
  {
    fixtureId: "f-single-byte",
    relativePath: "../fixtures/kernel-protocol-single-byte.json",
  },
  {
    fixtureId: "f-all-zero-bytes",
    relativePath: "../fixtures/kernel-protocol-all-zero-bytes.json",
  },
  {
    fixtureId: "f-all-ones-bytes",
    relativePath: "../fixtures/kernel-protocol-all-ones-bytes.json",
  },
  {
    fixtureId: "f-large-bytes",
    relativePath: "../fixtures/kernel-protocol-large-bytes.json",
  },
  {
    fixtureId: "f-multi-path-schema",
    relativePath: "../fixtures/kernel-protocol-multi-path-schema.json",
  },
  {
    fixtureId: "f-all-single-paths",
    relativePath: "../fixtures/kernel-protocol-all-single-paths-schema.json",
  },
  {
    fixtureId: "f-all-ordered-paths",
    relativePath: "../fixtures/kernel-protocol-all-ordered-paths-schema.json",
  },
  {
    fixtureId: "f-with-prev-turn",
    relativePath: "../fixtures/kernel-protocol-with-prev-turn.json",
  },
  {
    fixtureId: "f-with-event-hash",
    relativePath: "../fixtures/kernel-protocol-with-event-hash.json",
  },
  {
    fixtureId: "f-staged-failed",
    relativePath: "../fixtures/kernel-protocol-staged-result-failed.json",
  },
  {
    fixtureId: "f-staged-interrupted",
    relativePath: "../fixtures/kernel-protocol-staged-result-interrupted.json",
  },
  {
    fixtureId: "f-many-staged-results",
    relativePath: "../fixtures/kernel-protocol-many-staged-results.json",
  },
  {
    fixtureId: "f-deep-path-schema",
    relativePath: "../fixtures/kernel-protocol-deep-path-schema.json",
  },
  {
    fixtureId: "f-non-utf8-bytes",
    relativePath: "../fixtures/kernel-protocol-non-utf8-bytes.json",
  },
  {
    fixtureId: "f-zero-turn-tree-hash",
    relativePath: "../fixtures/kernel-protocol-zero-turn-tree-hash.json",
  },
  {
    fixtureId: "f-mixed-status-staged",
    relativePath: "../fixtures/kernel-protocol-mixed-status-staged-results.json",
  },
];

await main();

async function main(): Promise<void> {
  // Probe plans for the 21 unimplemented kernel syscalls were removed: the
  // shared plan validator only accepts operations declared in the kernel
  // operation source, so forward-looking probes against undeclared operations
  // would block the codegen/verify gate. Bringing those operations under
  // authority is a separate spec amendment.
  const extendedPlan = buildExtendedProtocolPlan();

  await writeFile(
    resolve(PLANS_DIR, "kernel-protocol-extended.json"),
    `${JSON.stringify(extendedPlan, null, 2)}\n`
  );

  process.stdout.write(
    `wrote kernel-protocol-extended.json (${extendedPlan.checks.length} checks)\n`
  );
}

function buildExtendedProtocolPlan(): {
  applicability: { capabilities: string[] };
  checks: PlanCheck[];
  fixtures: Record<string, string>;
  packetId: string;
  planId: string;
  planVersion: string;
} {
  const checks: PlanCheck[] = [];

  for (const fixture of fixtures) {
    checks.push(
      buildDeterministicHashingCheck(fixture),
      buildSchemaRoundtripCheck(fixture)
    );
  }

  return {
    applicability: { capabilities: ["kernel.protocol"] },
    checks,
    fixtures: Object.fromEntries(
      fixtures.map((entry) => [entry.fixtureId, entry.relativePath])
    ),
    packetId: "tuvren.kernel.protocol",
    planId: "tuvren.kernel.protocol.extended",
    planVersion: "0.1.0",
  };
}

function buildDeterministicHashingCheck(fixture: FixtureEntry): PlanCheck {
  return {
    assertions: [
      {
        equalsPath: "$.fixture.rawOpaqueBytesSha256Hex",
        field: "$.hashes.rawOpaqueBytes",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnTreeSchemaRecordSha256Hex",
        field: "$.hashes.turnTreeSchema",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnNodeIdentityRecordSha256Hex",
        field: "$.hashes.turnNodeIdentity",
        kind: "evidenceField",
      },
    ],
    checkId: `kernel.protocol.deterministic_hashing.${fixture.fixtureId}`,
    evidence: [
      "hashes.rawOpaqueBytes",
      "hashes.turnTreeSchema",
      "hashes.turnNodeIdentity",
    ],
    fixture: fixture.fixtureId,
    operation: "kernel.protocol.deterministic-hashing",
  };
}

function buildSchemaRoundtripCheck(fixture: FixtureEntry): PlanCheck {
  return {
    assertions: [
      {
        equalsPath: "$.fixture.turnTreeSchemaRecord.schemaId",
        field: "$.roundtrip.turnTreeSchemaRecord.schemaId",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnNodeIdentityRecord.schemaId",
        field: "$.roundtrip.turnNodeIdentityRecord.schemaId",
        kind: "evidenceField",
      },
      {
        equalsPath: "$.fixture.turnNodeIdentityRecord.turnTreeHash",
        field: "$.roundtrip.turnNodeIdentityRecord.turnTreeHash",
        kind: "evidenceField",
      },
    ],
    checkId: `kernel.protocol.schema_roundtrip.${fixture.fixtureId}`,
    evidence: [
      "roundtrip.turnTreeSchemaRecord.schemaId",
      "roundtrip.turnNodeIdentityRecord.schemaId",
      "roundtrip.turnNodeIdentityRecord.turnTreeHash",
    ],
    fixture: fixture.fixtureId,
    operation: "kernel.protocol.schema-roundtrip",
  };
}

