/**
 * Copyright 2026 Oscar Yáñez Cisterna (@SkrOYC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// biome-ignore-all lint/performance/noBarrelFile: This package entrypoint is the intentional public contract surface.
export {
  canonicalizeKernelRecord,
  decodeDeterministicKernelRecord,
  encodeDeterministicKernelRecord,
  hashKernelRecord,
  hashOpaqueObjectBytes,
  hashTurnNodeIdentity,
  hashTurnTreeIdentity,
} from "./lib/kernel-identity.js";
export type {
  AbortVerdict,
  BranchHeadListEntry,
  BranchRecord,
  BranchRepository,
  ComposedVerdict,
  IncorporationRule,
  InterruptedStagedResult,
  InterruptedStoredStagedResult,
  KernelSignal,
  ModifyVerdict,
  ObserveAnnotationRepository,
  ObjectRepository,
  ObserveResult,
  OrderedPathChunkRepository,
  PathCollectionKind,
  PathDefinition,
  PathValue,
  PauseVerdict,
  ProceedVerdict,
  RecoveryState,
  RetryVerdict,
  RunCompletionStatus,
  RunRecord,
  RunRepository,
  RunStatus,
  RuntimeBackend,
  RuntimeBackendTx,
  RuntimeKernel,
  SchemaRepository,
  SetHeadResult,
  SettledStagedResult,
  SettledStoredStagedResult,
  StagedResult,
  StagedResultRepository,
  StagedResultStatus,
  StepContext,
  StepDeclaration,
  StoredBranch,
  StoredObserveAnnotation,
  StoredChunkedOrderedTurnTreePath,
  StoredFlatOrderedTurnTreePath,
  StoredObject,
  StoredOrderedPathChunk,
  StoredRun,
  StoredSchema,
  StoredSingleTurnTreePath,
  StoredStagedResult,
  StoredThread,
  StoredTurn,
  StoredTurnNode,
  StoredTurnTree,
  StoredTurnTreePath,
  ThreadCreateResult,
  ThreadRecord,
  ThreadRepository,
  TurnNode,
  TurnNodeRepository,
  TurnRecord,
  TurnRepository,
  TurnTreeChangeSet,
  TurnTreeManifest,
  TurnTreePathRepository,
  TurnTreeRepository,
  TurnTreeSchema,
  Verdict,
  VerdictDisposition,
} from "./lib/kernel-types.js";
export {
  assertBranchHeadListEntry,
  assertBranchRecord,
  assertComposedVerdict,
  assertObserveResult,
  assertPathCollectionKind,
  assertPathValue,
  assertPathValueForCollectionKind,
  assertRecoveryState,
  assertRunCompletionStatus,
  assertRunRecord,
  assertRunStatus,
  assertSetHeadResult,
  assertStagedResult,
  assertStagedResultStatus,
  assertStepContext,
  assertStepDeclaration,
  assertStoredBranch,
  assertStoredObserveAnnotation,
  assertStoredObject,
  assertStoredObjectIdentity,
  assertStoredOrderedPathChunk,
  assertStoredOrderedPathChunkIdentity,
  assertStoredRun,
  assertStoredSchema,
  assertStoredStagedResult,
  assertStoredThread,
  assertStoredTurn,
  assertStoredTurnNode,
  assertStoredTurnNodeIdentity,
  assertStoredTurnTree,
  assertStoredTurnTreeIdentity,
  assertStoredTurnTreePath,
  assertThreadCreateResult,
  assertThreadRecord,
  assertTurnNode,
  assertTurnNodeIdentity,
  assertTurnRecord,
  assertTurnTreeChangeSet,
  assertTurnTreeManifest,
  assertTurnTreeSchema,
  assertVerdict,
  assertVerdictDisposition,
  isBranchHeadListEntry,
  isBranchRecord,
  isComposedVerdict,
  isObserveResult,
  isPathCollectionKind,
  isPathValue,
  isRecoveryState,
  isRunCompletionStatus,
  isRunRecord,
  isRunStatus,
  isSetHeadResult,
  isStagedResult,
  isStagedResultStatus,
  isStepContext,
  isStepDeclaration,
  isStoredBranch,
  isStoredObserveAnnotation,
  isStoredObject,
  isStoredOrderedPathChunk,
  isStoredRun,
  isStoredSchema,
  isStoredStagedResult,
  isStoredThread,
  isStoredTurn,
  isStoredTurnNode,
  isStoredTurnTree,
  isStoredTurnTreePath,
  isThreadCreateResult,
  isThreadRecord,
  isTurnNode,
  isTurnRecord,
  isTurnTreeSchema,
  isVerdict,
  isVerdictDisposition,
} from "./lib/kernel-validation.js";
