/**
 * Copyright 2026 Oscar Yáñez Cisterna (@SkrOYC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// biome-ignore-all lint/performance/noBarrelFile: This package entrypoint is the intentional public contract surface.
export type {
  EpochMs,
  HashString,
  KernelRecord,
} from "@kraken/shared-core-types";
export { KrakenValidationError } from "@kraken/shared-core-types";
// Focused facade packages are the preferred import homes for event, tool,
// provider, and driver-specific contracts. These re-exports remain here as a
// compatibility bridge while the partitioned surface settles across packages.
export type {
  AfterIterationContext,
  AfterIterationHandler,
  AgentConfig,
  ApprovalDecision,
  ApprovalDecisionType,
  ApprovalPolicy,
  ApprovalRequest,
  ApprovalRequestedEvent,
  ApprovalResolvedEvent,
  ApprovalResponse,
  AroundModelContext,
  AroundModelHandler,
  AroundModelResult,
  AroundToolContext,
  AroundToolHandler,
  AroundToolResult,
  AroundToolSpec,
  ContentPart,
  ContextEngineeringContext,
  ContextEngineeringHelpers,
  ContextEngineeringPlan,
  ContextManifest,
  ContextManifestCounters,
  ContextManifestNameCounters,
  ContextPolicy,
  ContextPolicyResult,
  CustomEvent,
  CustomSchema,
  DriverAttributedEventSource,
  ErrorEvent,
  EventSource,
  ExecuteFunction,
  ExecutionHandle,
  ExecutionStatus,
  ExtensionContext,
  FilePart,
  HandoffContextBuilder,
  HandoffContextMode,
  HandoffContextPlan,
  HandoffSourceContext,
  InputSignal,
  InterceptContext,
  InterceptHandler,
  InterceptResult,
  IterationDecision,
  IterationEndEvent,
  IterationStartEvent,
  KrakenErrorProjection,
  KrakenExtension,
  KrakenJsonSchema,
  KrakenMessage,
  KrakenModelConfig,
  KrakenModelResponse,
  KrakenPrompt,
  KrakenProvider,
  KrakenRuntime,
  KrakenStreamEvent,
  KrakenToolDefinition,
  KrakenToolResultBatch,
  LoopPolicy,
  MessageDoneEvent,
  MessageStartEvent,
  OrchestrationHandle,
  OrchestrationRuntime,
  PendingToolCall,
  ProviderStreamChunk,
  ProviderUsage,
  ReasoningDeltaEvent,
  ReasoningDoneEvent,
  ReasoningPart,
  RenderedToolDefinition,
  RuntimeResolution,
  StateCheckpointEvent,
  StateSnapshotEvent,
  SteeringIncorporatedEvent,
  StructuredDeltaEvent,
  StructuredDoneEvent,
  StructuredOutputRequest,
  StructuredPart,
  SystemPromptContext,
  SystemPromptFn,
  TextDeltaEvent,
  TextDoneEvent,
  TextPart,
  ToolCallArgsDeltaEvent,
  ToolCallDoneEvent,
  ToolCallPart,
  ToolCallStartEvent,
  ToolDispatchContext,
  ToolExecutionContext,
  ToolExecutionResult,
  ToolRegistry,
  ToolResultEvent,
  ToolResultPart,
  ToolStartEvent,
  TurnEndEvent,
  TurnStartEvent,
  ValidationErrorPayload,
  ValidationResult,
  WorkerStatus,
} from "./lib/runtime-contracts.js";
export {
  assertApprovalRequest,
  assertApprovalResponse,
  assertApprovalResponseForRequest,
  assertContextManifest,
  assertExecutionStatus,
  assertKrakenMessage,
  assertKrakenStreamEvent,
  assertKrakenToolDefinition,
  assertProviderStreamChunk,
  isApprovalRequest,
  isApprovalResponse,
  isApprovalResponseForRequest,
  isExecutionStatus,
  isKrakenMessage,
  isKrakenStreamEvent,
  isKrakenToolDefinition,
  isProviderStreamChunk,
} from "./lib/runtime-contracts.js";
