/**
 * Copyright 2026 Oscar Yáñez Cisterna (@SkrOYC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// biome-ignore-all lint/performance/noBarrelFile: This package entrypoint is the intentional public contract surface.
export {
  canonicalizeKernelRecord,
  decodeDeterministicKernelRecord,
  encodeDeterministicKernelRecord,
  hashKernelRecord,
  hashOpaqueObjectBytes,
} from "./lib/kernel-identity.js";
export type {
  BranchHeadListEntry,
  BranchRecord,
  IncorporationRule,
  KrakenKernel,
  ObserveResult,
  PathCollectionKind,
  PathDefinition,
  PathValue,
  RecoveryState,
  RunCompletionStatus,
  RunRecord,
  RunStatus,
  SetHeadResult,
  StagedResult,
  StagedResultStatus,
  StepContext,
  StepDeclaration,
  StoredBranch,
  StoredObject,
  StoredOrderedPathChunk,
  StoredRun,
  StoredSchema,
  StoredStagedResult,
  StoredThread,
  StoredTurn,
  StoredTurnNode,
  StoredTurnTree,
  StoredTurnTreePath,
  ThreadCreateResult,
  ThreadRecord,
  TurnNode,
  TurnRecord,
  TurnTreeChangeSet,
  TurnTreeManifest,
  TurnTreeSchema,
} from "./lib/kernel-types.js";
export {
  assertBranchRecord,
  assertObserveResult,
  assertPathCollectionKind,
  assertPathValue,
  assertPathValueForCollectionKind,
  assertRecoveryState,
  assertRunCompletionStatus,
  assertRunRecord,
  assertRunStatus,
  assertSetHeadResult,
  assertStagedResult,
  assertStagedResultStatus,
  assertStepContext,
  assertStepDeclaration,
  assertStoredBranch,
  assertStoredObject,
  assertStoredObjectIdentity,
  assertStoredOrderedPathChunk,
  assertStoredRun,
  assertStoredSchema,
  assertStoredStagedResult,
  assertStoredThread,
  assertStoredTurn,
  assertStoredTurnNode,
  assertStoredTurnTree,
  assertStoredTurnTreeIdentity,
  assertStoredTurnTreePath,
  assertThreadCreateResult,
  assertThreadRecord,
  assertTurnNode,
  assertTurnRecord,
  assertTurnTreeChangeSet,
  assertTurnTreeManifest,
  assertTurnTreeSchema,
  isBranchRecord,
  isObserveResult,
  isPathCollectionKind,
  isPathValue,
  isRecoveryState,
  isRunCompletionStatus,
  isRunRecord,
  isRunStatus,
  isSetHeadResult,
  isStagedResult,
  isStagedResultStatus,
  isStepContext,
  isStepDeclaration,
  isStoredBranch,
  isStoredObject,
  isStoredOrderedPathChunk,
  isStoredRun,
  isStoredSchema,
  isStoredStagedResult,
  isStoredThread,
  isStoredTurn,
  isStoredTurnNode,
  isStoredTurnTree,
  isStoredTurnTreePath,
  isThreadCreateResult,
  isThreadRecord,
  isTurnNode,
  isTurnRecord,
  isTurnTreeSchema,
} from "./lib/kernel-validation.js";
