/**
 * Copyright 2026 Oscar Yáñez Cisterna (@SkrOYC)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// biome-ignore-all lint/performance/noBarrelFile: This package subpath is the intentional focused contract surface.

export {
  assertApprovalRequest,
  assertApprovalResponse,
  assertApprovalResponseForRequest,
  assertContextManifest,
  assertExecutionStatus,
  assertProviderStreamChunk,
  assertTuvrenMessage,
  assertTuvrenModelResponse,
  assertTuvrenStreamEvent,
  assertTuvrenToolDefinition,
  isApprovalRequest,
  isApprovalResponse,
  isApprovalResponseForRequest,
  isExecutionStatus,
  isProviderStreamChunk,
  isTuvrenMessage,
  isTuvrenModelResponse,
  isTuvrenStreamEvent,
  isTuvrenToolDefinition,
} from "./runtime-contract-guards.js";
export type {
  AfterIterationContext,
  AfterIterationHandler,
  AgentConfig,
  ApprovalDecision,
  ApprovalDecisionType,
  ApprovalPolicy,
  ApprovalRequest,
  ApprovalRequestedEvent,
  ApprovalResolvedEvent,
  ApprovalResponse,
  AroundModelContext,
  AroundModelHandler,
  AroundModelResult,
  AroundToolContext,
  AroundToolHandler,
  AroundToolResult,
  AroundToolSpec,
  BranchMessagesCursor,
  BranchSummary,
  ContentPart,
  ContextEngineeringContext,
  ContextEngineeringHelpers,
  ContextEngineeringPlan,
  ContextManifest,
  ContextManifestCounters,
  ContextManifestNameCounters,
  ContextPolicy,
  ContextPolicyResult,
  CustomEvent,
  CustomSchema,
  DriverAttributedEventSource,
  ErrorEvent,
  EventSource,
  ExecuteFunction,
  ExecutionHandle,
  ExecutionResult,
  ExecutionStatus,
  ExtensionContext,
  FileDoneEvent,
  FilePart,
  HandoffContextBuilder,
  HandoffContextMode,
  HandoffContextPlan,
  HandoffSourceContext,
  InputSignal,
  InterceptContext,
  InterceptHandler,
  InterceptResult,
  IterationDecision,
  IterationEndEvent,
  IterationStartEvent,
  ListThreadsCursor,
  LoopPolicy,
  MessageDoneEvent,
  MessageStartEvent,
  OrchestrationHandle,
  OrchestrationResult,
  OrchestrationRuntime,
  PendingToolCall,
  ProviderStreamChunk,
  ProviderUsage,
  ReasoningDeltaEvent,
  ReasoningDoneEvent,
  ReasoningPart,
  RenderedToolDefinition,
  RuntimeResolution,
  StateCheckpointEvent,
  StateSnapshotEvent,
  SteeringIncorporatedEvent,
  StructuredDeltaEvent,
  StructuredDoneEvent,
  StructuredOutputRequest,
  StructuredPart,
  SystemPromptContext,
  SystemPromptFn,
  TextDeltaEvent,
  TextDoneEvent,
  TextPart,
  ThreadSummary,
  ToolCallArgsDeltaEvent,
  ToolCallDoneEvent,
  ToolCallPart,
  ToolCallStartEvent,
  ToolDispatchContext,
  ToolExecutionContext,
  ToolExecutionResult,
  ToolRegistry,
  ToolResultEvent,
  ToolResultPart,
  ToolStartEvent,
  TurnEndEvent,
  TurnHistoryCursor,
  TurnSnapshot,
  TurnStartEvent,
  TuvrenErrorProjection,
  TuvrenExtension,
  TuvrenJsonSchema,
  TuvrenJsonValue,
  TuvrenMessage,
  TuvrenModelConfig,
  TuvrenModelResponse,
  TuvrenPrompt,
  TuvrenProvider,
  TuvrenRuntime,
  TuvrenStreamEvent,
  TuvrenToolDefinition,
  TuvrenToolResultBatch,
  ValidationErrorPayload,
  ValidationResult,
} from "./runtime-contract-shapes.js";
